services:
  - type: web
    name: breaking-news-service
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: singapore # or oregon, frankfurt, etc.
    envVars:
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: DATA_DIR
        value: /app/data
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
